'use client';

import type { ChangeEvent } from 'react';
import { rosterSize, type DraftBoardCell } from '@/lib/board';
import { draftSlotForOverallPick } from '@/lib/draft';
import { teamDisplayName } from '@/lib/setup';
import type { AvailabilityLabel, DraftConfig, DraftPick, DraftStrategy, PlayerRanking, Recommendation, ScoringFormat } from '@/lib/types';

export type PlayerFilter='ALL'|'FAVORITES'|'DRAFTED'|PlayerRanking['position'];
export type PlayerSort='RANK'|'ADP'|'NAME';
export type Correction={overallPick:number;originalPick:DraftPick};
export const FILTERS:PlayerFilter[]=['ALL','FAVORITES','DRAFTED','QB','RB','WR','TE','K','DST'];
export const STRATEGIES:Array<[DraftStrategy,string]>=[['BALANCED','Balanced'],['HERO_RB','Hero RB'],['ZERO_RB','Zero RB'],['ROBUST_RB','Robust RB'],['WR_HEAVY','WR Heavy'],['LATE_QB','Late QB'],['ELITE_TE','Elite TE'],['UPSIDE_HEAVY','Upside Heavy']];
export const ROSTER:Array<[keyof Pick<DraftConfig,'qbStarters'|'rbStarters'|'wrStarters'|'teStarters'|'flexStarters'|'dstStarters'|'kStarters'|'benchSpots'>,string,number]>=[['qbStarters','QB',10],['rbStarters','RB',10],['wrStarters','WR',10],['teStarters','TE',10],['flexStarters','FLEX',10],['dstStarters','DST',10],['kStarters','K',10],['benchSpots','Bench',20]];

export interface DraftUiProps {
  config:DraftConfig; players:PlayerRanking[]; picks:DraftPick[]; favorites:Set<string>; teamNames:string[]; started:boolean; correction:Correction|null; correcting:boolean;
  complete:boolean; totalPicks:number; currentOverallPick:number; currentRound:number; currentPickInRound:number; currentSlot:number|null; historicalGap:boolean; nextUserPick:number|null; onClock:boolean;
  message:string; error:string|null; storage:string|null; startError:string|null; visible:PlayerRanking[]; filter:PlayerFilter; sort:PlayerSort; search:string; board:DraftBoardCell[][]; recs:Recommendation[]; userRoster:PlayerRanking[]; strategyLabel:string;
  onImport:(e:ChangeEvent<HTMLInputElement>)=>void; onRestore:(e:ChangeEvent<HTMLInputElement>)=>void; onBackup:()=>void; onUndo:()=>void; onRestart:()=>void; onCancelCorrection:()=>void; onStart:()=>void;
  onTeamCount:(n:number)=>void; onSlot:(n:number)=>void; onScoring:(v:ScoringFormat)=>void; onStrategy:(v:DraftStrategy)=>void; onRoster:(k:(typeof ROSTER)[number][0],n:number,max:number)=>void; onTeamName:(i:number,v:string)=>void;
  onFilter:(v:PlayerFilter)=>void; onSort:(v:PlayerSort)=>void; onSearch:(v:string)=>void; onFavorite:(id:string)=>void; onDraft:(p:PlayerRanking)=>void; onCorrect:(p:DraftPick,remove?:boolean)=>void;
}

export function DraftUi(p:DraftUiProps){const team=(s:number)=>teamDisplayName(s,p.config.userDraftSlot,p.teamNames);return <main className="shell">
  <header className="hero"><div><div className="eyebrow">RosterPilot</div><h1>Draft Companion</h1><p>Import rankings, enter picks live, and get three transparent recommendations.</p></div><div className="statusActions"><FileLabel text={p.started?'Rankings locked':'Import rankings'} disabled={p.started} accept=".xlsx,.xls,.csv" onChange={p.onImport}/><button className="secondaryButton" onClick={p.onBackup} disabled={!p.players.length}>Download backup</button><FileLabel text="Restore backup" accept=".json,application/json" onChange={p.onRestore}/></div></header>
  <section className="statusBar"><Status label="Current" value={!p.started?'Setup':p.correction?`Correcting #${p.correction.overallPick}`:p.historicalGap?`Correction needed #${p.currentOverallPick}`:p.complete?'Draft complete':`R${p.currentRound} • ${p.currentRound}.${String(p.currentPickInRound).padStart(2,'0')}`}/><Status label="Overall pick" value={!p.started?`0/${p.totalPicks}`:p.correction?`#${p.correction.overallPick}`:p.complete?`${p.totalPicks}/${p.totalPicks}`:`${p.currentOverallPick}/${p.totalPicks}`}/><Status label="On the clock" value={!p.started||p.complete?'—':p.correction?team(draftSlotForOverallPick(p.correction.overallPick,p.config.teamCount)):p.currentSlot?team(p.currentSlot):'—'} emphasis={p.onClock}/><Status label="Your next pick" value={p.correcting?'Paused':p.nextUserPick?`#${p.nextUserPick}`:'—'}/><div className="statusActions"><button className="secondaryButton" onClick={p.onUndo} disabled={!p.picks.length||p.correcting}>Undo last pick</button>{p.correction?<button className="secondaryButton" onClick={p.onCancelCorrection}>Cancel correction</button>:null}<button className="secondaryButton" onClick={p.onRestart} disabled={!p.started}>Restart / edit setup</button></div></section>
  <Setup p={p}/><Board p={p}/><div className="dashboardGrid"><Players p={p}/><aside className="sideStack"><Recommendations p={p}/><Roster p={p}/></aside></div><History p={p}/>
</main>}

function Setup({p}:{p:DraftUiProps}){return <section className={p.started?'setupPanel locked':'setupPanel'}><div className="setupHeader"><div><span className="eyebrow">League setup</span><h2>{p.started?'Draft settings locked':'Configure your draft'}</h2><p className="muted">{p.message}</p>{[p.error,p.storage,p.startError].filter(Boolean).map((x,i)=><p className="error" key={i}>{x}</p>)}</div><div className="setupStart"><span className={p.started?'setupState active':'setupState'}>{p.started?'LIVE':'SETUP'}</span><button className="primaryButton" onClick={p.onStart} disabled={p.started||!p.players.length||Boolean(p.startError)}>{!p.players.length?'Import rankings first':p.started?'Draft started':'Start draft'}</button></div></div><div className="setupControls setupPrimaryControls"><NumberField label="Teams" value={p.config.teamCount} disabled={p.started} min={4} max={20} onChange={p.onTeamCount}/><NumberField label="Your slot" value={p.config.userDraftSlot} disabled={p.started} min={1} max={p.config.teamCount} onChange={p.onSlot}/><label>Scoring<select value={p.config.scoringFormat} disabled={p.started} onChange={e=>p.onScoring(e.target.value as ScoringFormat)}><option value="STANDARD">Standard</option><option value="HALF_PPR">Half-PPR</option><option value="PPR">PPR</option></select></label><label>Strategy<select value={p.config.draftStrategy??'BALANCED'} onChange={e=>p.onStrategy(e.target.value as DraftStrategy)}>{STRATEGIES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><div className="rosterSetupGrid">{ROSTER.map(([k,l,m])=><NumberField key={k} label={l} value={p.config[k]} disabled={p.started} min={0} max={m} onChange={n=>p.onRoster(k,n,m)}/>)}</div><div className="teamNamesSection"><div className="teamNamesHeader"><strong>Team names</strong><span className="muted">Optional opponent labels.</span></div><div className="teamNameGrid">{Array.from({length:p.config.teamCount},(_,i)=><label className={i+1===p.config.userDraftSlot?'teamNameField userTeamName':'teamNameField'} key={i}><span>Slot {i+1}{i+1===p.config.userDraftSlot?' • YOU':''}</span><input disabled={p.started} value={p.teamNames[i]??''} placeholder={`Team ${i+1}`} onChange={e=>p.onTeamName(i,e.target.value)}/></label>)}</div></div></section>}
function Board({p}:{p:DraftUiProps}){const team=(s:number)=>teamDisplayName(s,p.config.userDraftSlot,p.teamNames);return <section className="panel draftBoardPanel"><PanelHeader eyebrow="Live draft" title="Draft board" pill={`${p.picks.length} / ${p.totalPicks} picks`}/><div className="draftBoardScroller"><div className="draftBoardHeader" style={{gridTemplateColumns:`64px repeat(${p.config.teamCount}, minmax(122px,1fr))`}}><div className="roundHeader">Rnd</div>{Array.from({length:p.config.teamCount},(_,i)=>{const s=i+1;return <div className={['teamHeader',s===p.config.userDraftSlot?'userTeam':'',p.started&&!p.complete&&s===(p.correction?draftSlotForOverallPick(p.correction.overallPick,p.config.teamCount):p.currentSlot)?'currentTeam':''].filter(Boolean).join(' ')} key={s}><strong>{team(s)}</strong><small>{p.picks.filter(x=>x.draftSlot===s).length}/{rosterSize(p.config)}</small></div>})}</div>{p.board.map((row,r)=><div className="draftBoardRow" style={{gridTemplateColumns:`64px repeat(${p.config.teamCount}, minmax(122px,1fr))`}} key={r}><div className="roundLabel">{r+1}</div>{row.map(c=><div id={`draft-cell-${c.overallPick}`} className={['draftCell',p.started&&!p.complete&&c.overallPick===(p.correction?.overallPick??p.currentOverallPick)?'currentPick':'',c.draftSlot===p.config.userDraftSlot?'userCell':''].filter(Boolean).join(' ')} key={c.overallPick}><small>#{c.overallPick}</small>{c.player?<><strong>{c.player.name}</strong><span>{c.player.position}{c.player.nflTeam?` • ${c.player.nflTeam}`:''}</span>{c.pick?<div className="draftCellActions"><button disabled={p.correcting} onClick={()=>p.onCorrect(c.pick!)}>Edit</button><button disabled={p.correcting} onClick={()=>p.onCorrect(c.pick!,true)}>Remove</button></div>:null}</>:null}</div>)}</div>)}</div></section>}
function Players({p}:{p:DraftUiProps}){const byPlayer=new Map(p.picks.map(x=>[x.playerId,x]));const team=(s:number)=>teamDisplayName(s,p.config.userDraftSlot,p.teamNames);return <section className="panel playersPanel"><PanelHeader eyebrow="Player pool" title="Available players" pill={p.filter==='DRAFTED'?`${p.picks.length} drafted`:`${p.players.length-p.picks.length} available`}/>{p.correcting?<div className="correctionBanner"><strong>Correcting pick #{p.correction?.overallPick??p.currentOverallPick}</strong>{p.correction?<button className="secondaryButton" onClick={p.onCancelCorrection}>Cancel</button>:null}</div>:null}<div className="playerTools"><input className="searchInput" placeholder="Search player or team..." value={p.search} onChange={e=>p.onSearch(e.target.value)}/><label className="sortControl">Sort<select value={p.sort} onChange={e=>p.onSort(e.target.value as PlayerSort)}><option value="RANK">Rank</option><option value="ADP">ADP</option><option value="NAME">Name</option></select></label></div><div className="filters">{FILTERS.map(f=><button className={p.filter===f?'filter active':'filter'} key={f} onClick={()=>p.onFilter(f)}>{f==='FAVORITES'?'★ Favorites':f==='DRAFTED'?'Drafted':f}</button>)}</div><div className="playerList">{p.visible.slice(0,100).map(x=>{const pick=byPlayer.get(x.id),fav=p.favorites.has(x.id);return <div className={pick?'playerRow drafted':'playerRow'} key={x.id}><button className={fav?'favoriteButton active':'favoriteButton'} onClick={()=>p.onFavorite(x.id)}>{fav?'★':'☆'}</button><span className="rank">{x.overallRank}</span><span className="playerIdentity"><strong>{x.name}</strong><small>{x.position}{x.nflTeam?` • ${x.nflTeam}`:''}{x.tier!=null?` • Tier ${x.tier}`:''}{x.adp!=null?` • ADP ${Math.round(x.adp)}`:''}</small></span><button className="draftPlayerButton" disabled={Boolean(pick)||!p.started||p.complete} onClick={()=>p.onDraft(x)}>{pick?`#${pick.overallPick} • ${team(pick.draftSlot)}`:p.correcting?`Use at #${p.correction?.overallPick??p.currentOverallPick}`:'Draft'}</button></div>})}{!p.visible.length?<EmptyState text={p.players.length?'No players match this view.':'Import rankings to begin.'}/>:null}</div></section>}
function Recommendations({p}:{p:DraftUiProps}){return <section className="panel recommendationPanel"><PanelHeader eyebrow="Decision engine" title="Top 3" pill="Recommendation %"/>{p.recs.length?<div className="recommendationList">{p.recs.map((r,i)=><article className="recommendation" key={r.player.id}><div className="recommendationTopline"><span className="medal">#{i+1}</span><div><strong>{p.favorites.has(r.player.id)?'★ ':''}{r.player.name}</strong><small>{r.player.position} • Rank {r.player.overallRank}</small></div><span className="score">{r.recommendationPercent}%</span></div><div className="scoreTrack"><span style={{width:`${r.recommendationPercent}%`}}/></div><div className="recommendationSignals"><span className={`signalChip availability ${r.availabilityLabel.toLowerCase()}`}>{availabilitySignal(r.availabilityLabel,r.returnPick)}</span>{r.positionTrend!=='QUIET'?<span className="signalChip">{r.positionTrend==='HOT'?'🔥':'↗'} {r.player.position} run</span>:null}{r.marketFall!=null?<span className="signalChip">Market fall +{Math.round(r.marketFall)}</span>:null}{r.breakdown.rosterFit>=90?<span className="signalChip">Starter need</span>:null}{p.favorites.has(r.player.id)?<span className="signalChip favorite">★ Favorite</span>:null}{(p.config.draftStrategy??'BALANCED')!=='BALANCED'&&r.breakdown.strategyFit>=85?<span className="signalChip">{p.strategyLabel} fit</span>:null}</div><ul>{r.reasons.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div>:<EmptyState text={p.complete?'Draft complete.':p.correcting?'Recommendations paused during correction.':!p.started?'Start the draft to activate recommendations.':'No recommendations available.'}/>}</section>}
function Roster({p}:{p:DraftUiProps}){return <section className="panel rosterPanel"><PanelHeader eyebrow={teamDisplayName(p.config.userDraftSlot,p.config.userDraftSlot,p.teamNames)} title="Your roster" pill={`${p.userRoster.length} / ${rosterSize(p.config)}`}/><div className="rosterList">{p.userRoster.length?p.userRoster.map(x=><div className="rosterRow" key={x.id}><span className="positionBadge">{x.position}</span><span>{x.name}</span></div>):<EmptyState text="Your drafted players will appear here."/>}</div></section>}
function History({p}:{p:DraftUiProps}){const byId=new Map(p.players.map(x=>[x.id,x]));return <section className="panel historyPanel"><PanelHeader eyebrow="Draft state" title="Recent picks" pill={`${p.picks.length} entered`}/><div className="historyGrid">{[...p.picks].reverse().slice(0,16).map(x=><div className={x.draftSlot===p.config.userDraftSlot?'historyPick userPick':'historyPick'} key={x.overallPick}><small>#{x.overallPick} • {teamDisplayName(x.draftSlot,p.config.userDraftSlot,p.teamNames)}</small><strong>{byId.get(x.playerId)?.name??x.playerId}</strong><span>{byId.get(x.playerId)?.position}</span><div className="historyActions"><button disabled={p.correcting} onClick={()=>p.onCorrect(x)}>Edit</button><button disabled={p.correcting} onClick={()=>p.onCorrect(x,true)}>Remove</button></div></div>)}{!p.picks.length?<EmptyState text="No picks entered yet."/>:null}</div></section>}
function availabilitySignal(l:AvailabilityLabel,n?:number){return l==='UNLIKELY'?(n?`Unlikely back by #${n}`:'Unlikely to return'):l==='LIKELY'?(n?`Likely back by #${n}`:'Likely to return'):l==='UNCERTAIN'?(n?`Return uncertain by #${n}`:'Return uncertain'):'Final selection'}
function Status({label,value,emphasis=false}:{label:string;value:string;emphasis?:boolean}){return <div className={emphasis?'status emphasis':'status'}><small>{label}</small><strong>{value}</strong></div>}
function PanelHeader({eyebrow,title,pill}:{eyebrow:string;title:string;pill:string}){return <div className="panelHeader"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span className="countPill">{pill}</span></div>}
function EmptyState({text}:{text:string}){return <div className="emptyState">{text}</div>}
function NumberField({label,value,disabled,min,max,onChange}:{label:string;value:number;disabled:boolean;min:number;max:number;onChange:(n:number)=>void}){return <label><span>{label}</span><input type="number" value={value} disabled={disabled} min={min} max={max} onChange={e=>onChange(Number(e.target.value))}/></label>}
function FileLabel({text,accept,onChange,disabled=false}:{text:string;accept:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void;disabled?:boolean}){return <label className={disabled?'uploadButton disabled':'secondaryButton'}>{text}<input type="file" accept={accept} onChange={onChange} disabled={disabled} hidden/></label>}
