'use client';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { buildDraftBoard, rosterForSlot } from '@/lib/board';
import { replaceDraftPick, removeDraftPick } from '@/lib/corrections';
import { nextUserOverallPick } from '@/lib/draft';
import { DRAFT_STORAGE_KEY, parseDraftSnapshot, serializeDraftSnapshot } from '@/lib/persistence';
import { validateRankingPool } from '@/lib/preflight';
import { recommendPlayers } from '@/lib/recommendation';
import { deriveDraftSession } from '@/lib/session';
import { defaultTeamNames, resizeTeamNames, validateDraftSetup } from '@/lib/setup';
import { parseRankingFile } from '@/lib/spreadsheet';
import { defaultStrategyForDraftSlot } from '@/lib/strategy';
import { DraftUi, STRATEGIES, type Correction, type PlayerFilter, type PlayerSort } from './draft-ui';
import type { DraftConfig, DraftPick, DraftStrategy, PlayerRanking, ScoringFormat } from '@/lib/types';

const DEFAULT:DraftConfig={teamCount:10,userDraftSlot:7,scoringFormat:'HALF_PPR',qbStarters:1,rbStarters:2,wrStarters:3,teStarters:1,flexStarters:1,dstStarters:1,kStarters:1,benchSpots:6,draftStrategy:'BALANCED'};
export default function Page(){
 const [config,setConfig]=useState(DEFAULT),[players,setPlayers]=useState<PlayerRanking[]>([]),[picks,setPicks]=useState<DraftPick[]>([]),[favoriteIds,setFavoriteIds]=useState<string[]>([]),[teamNames,setTeamNames]=useState(()=>defaultTeamNames(10)),[started,setStarted]=useState(false),[correction,setCorrection]=useState<Correction|null>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState<PlayerFilter>('ALL'),[sort,setSort]=useState<PlayerSort>('RANK'),[message,setMessage]=useState('Upload your rankings to begin.'),[error,setError]=useState<string|null>(null),[storage,setStorage]=useState<string|null>(null),[hydrated,setHydrated]=useState(false);
 const setup=useMemo(()=>validateDraftSetup(config),[config]),preflight=useMemo(()=>validateRankingPool(players,config),[players,config]),session=useMemo(()=>deriveDraftSession(picks,config,started),[picks,config,started]);
 const correcting=Boolean(correction)||session.historicalGap,nextUserPick=!started||session.complete?null:nextUserOverallPick(session.currentOverallPick,config),favorites=useMemo(()=>new Set(favoriteIds),[favoriteIds]),drafted=useMemo(()=>new Set(picks.map(x=>x.playerId)),[picks]);
 const board=useMemo(()=>buildDraftBoard(config,picks,players),[config,picks,players]),userRoster=useMemo(()=>rosterForSlot(config.userDraftSlot,picks,players),[config.userDraftSlot,picks,players]),recs=useMemo(()=>!started||session.complete||correcting?[]:recommendPlayers({players,picks,config,currentOverallPick:session.currentOverallPick,favoritePlayerIds:favoriteIds,limit:3}),[started,session.complete,session.currentOverallPick,correcting,players,picks,config,favoriteIds]);
 const visible=useMemo(()=>players.filter(x=>{const d=drafted.has(x.id);if(filter==='DRAFTED'?!d:d)return false;if(filter==='FAVORITES'&&!favorites.has(x.id))return false;if(!['ALL','FAVORITES','DRAFTED'].includes(filter)&&x.position!==filter)return false;const q=search.trim().toLowerCase();return !q||x.name.toLowerCase().includes(q)||x.position.toLowerCase().includes(q)||Boolean(x.nflTeam?.toLowerCase().includes(q))}).sort((a,b)=>sort==='NAME'?a.name.localeCompare(b.name)||a.overallRank-b.overallRank:sort==='ADP'?(a.adp??Infinity)-(b.adp??Infinity)||a.overallRank-b.overallRank:a.overallRank-b.overallRank),[players,drafted,filter,favorites,search,sort]);
 function restore(s:NonNullable<ReturnType<typeof parseDraftSnapshot>>){setConfig(s.config);setPlayers(s.players);setPicks(s.picks);setFavoriteIds(s.favoritePlayerIds);setTeamNames(s.teamNames);setStarted(s.draftStarted);setCorrection(null);setMessage(`Restored ${s.players.length} players • ${s.picks.length} picks saved`)}
 useEffect(()=>{try{const raw=localStorage.getItem(DRAFT_STORAGE_KEY),s=raw?parseDraftSnapshot(raw):null;if(s)restore(s);else if(raw)setStorage('Saved draft data was invalid. Restore a JSON backup if available.')}catch{setStorage('Browser storage is unavailable. Download JSON backups during the draft.')}finally{setHydrated(true)}// eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(DRAFT_STORAGE_KEY,serializeDraftSnapshot({config,players,picks,favoritePlayerIds:favoriteIds,teamNames,draftStarted:started}));setStorage(null)}catch{setStorage('Could not save to browser storage. Download a JSON backup now.')}},[hydrated,config,players,picks,favoriteIds,teamNames,started]);
 useEffect(()=>{if(started)document.getElementById(`draft-cell-${correction?.overallPick??session.currentOverallPick}`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})},[started,session.currentOverallPick,correction?.overallPick]);
 async function importRankings(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||started)return;try{setError(null);const r=await parseRankingFile(f);setPlayers(r.players);setPicks([]);const ids=new Set(r.players.map(x=>x.id));setFavoriteIds(x=>x.filter(id=>ids.has(id)));const n=r.players.filter(x=>x.sourceMetadata?.adpSource==='DERIVED_ECR_VS_ADP').length;setMessage(`${r.players.length} players imported${r.detectedSource?` from ${r.detectedSource}`:''}${n?` • market ADP estimated for ${n}`:''}`)}catch(x){setError(x instanceof Error?x.message:'Unable to import rankings.')}finally{e.target.value=''}}
 async function restoreBackup(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{const s=parseDraftSnapshot(await f.text());if(!s)throw new Error('This backup is invalid or incompatible.');if(started&&!confirm('Replace the current draft with this backup?'))return;restore(s);setStorage('Backup restored successfully.')}catch(x){setError(x instanceof Error?x.message:'Unable to restore backup.')}finally{e.target.value=''}}
 function backup(){const raw=serializeDraftSnapshot({config,players,picks,favoritePlayerIds:favoriteIds,teamNames,draftStarted:started}),url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`rosterpilot-draft-backup-${Date.now()}.json`;a.click();URL.revokeObjectURL(url)}
 function correct(x:DraftPick,remove=false){if(correcting)return;if(remove&&!confirm(`Remove pick #${x.overallPick}?`))return;setCorrection({overallPick:x.overallPick,originalPick:x});if(remove)setPicks(p=>removeDraftPick(p,x.overallPick));setFilter('ALL')}
 const startError=!setup.valid?setup.errors[0]:players.length&&!preflight.valid?preflight.errors[0]:null,strategyLabel=STRATEGIES.find(([v])=>v===(config.draftStrategy??'BALANCED'))?.[1]??'Balanced';
 return <DraftUi config={config} players={players} picks={picks} favorites={favorites} teamNames={teamNames} started={started} correction={correction} correcting={correcting} {...session} nextUserPick={nextUserPick} onClock={started&&!correcting&&session.currentSlot===config.userDraftSlot} message={message} error={error} storage={storage} startError={startError} visible={visible} filter={filter} sort={sort} search={search} board={board} recs={recs} userRoster={userRoster} strategyLabel={strategyLabel}
 onImport={importRankings} onRestore={restoreBackup} onBackup={backup} onUndo={()=>setPicks(x=>[...x].sort((a,b)=>a.overallPick-b.overallPick).slice(0,-1))} onRestart={()=>{if(started&&!confirm('Restart the draft and unlock setup?'))return;setPicks([]);setCorrection(null);setStarted(false)}} onCancelCorrection={()=>{if(!correction)return;setPicks(x=>x.some(p=>p.overallPick===correction.overallPick)?x:[...x,correction.originalPick].sort((a,b)=>a.overallPick-b.overallPick));setCorrection(null)}} onStart={()=>setup.valid&&preflight.valid&&setStarted(true)}
 onTeamCount={n=>{const teamCount=Math.min(20,Math.max(4,Math.trunc(n||10)));setTeamNames(x=>resizeTeamNames(x,teamCount));setConfig(c=>{const s=Math.min(c.userDraftSlot,teamCount);return{...c,teamCount,userDraftSlot:s,draftStrategy:defaultStrategyForDraftSlot(s)}})}} onSlot={n=>{const s=Math.min(config.teamCount,Math.max(1,n||1));setConfig(c=>({...c,userDraftSlot:s,draftStrategy:defaultStrategyForDraftSlot(s)}))}} onScoring={(v:ScoringFormat)=>setConfig(c=>({...c,scoringFormat:v}))} onStrategy={(v:DraftStrategy)=>setConfig(c=>({...c,draftStrategy:v}))} onRoster={(k,n,m)=>setConfig(c=>({...c,[k]:Math.min(m,Math.max(0,Math.trunc(n||0)))}))} onTeamName={(i,v)=>setTeamNames(x=>{const n=resizeTeamNames(x,config.teamCount);n[i]=v.slice(0,32);return n})}
 onFilter={setFilter} onSort={setSort} onSearch={setSearch} onFavorite={id=>setFavoriteIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])} onDraft={x=>{if(!started||session.complete||drafted.has(x.id))return;setPicks(p=>replaceDraftPick(p,correction?.overallPick??session.currentOverallPick,x.id,config.teamCount));setCorrection(null);setSearch('')}} onCorrect={correct}/>;
}
